### ISSUE TITLE
HowTorun

### ISSUE THREAD

**Issue by NewToCodingDontMakeFunOfMe** [VirxEC/rl_ball_sym#9]
Sorry for being a noob to coding but i just recently installed cargo and im looking through all of the files, Which file do i run on cargo to see the ball predictions on rocket league ?

**Comment by VirxEC** [comment]
This actually isn't attached in any way to the game, but it is possible! Check out https://github.com/VirxEC/rl_ball_sym_pybinds/ (it might say 0.6 but that's wrong I'll update everything soon) and https://rlbot.org/ - tldr download the repo, load the folder into rlbot, and check off running the rl_ball_sym script and launch the game.

**Comment by NewToCodingDontMakeFunOfMe** [comment]
ohh lmao thought it was :D thanks for responding <3
